from .auth import router as auth_router
from .users import router as users_router
from .products import router as products_router
from .orders import router as orders_router
from .payment import router as payments_router
from .cart import router as cart_router
from .wishlist import router as wishlist_router
from .reviews import router as reviews_router
from .profile import router as profile_router
from .category import router as category_router